# Generated by Django 4.2.1 on 2023-05-31 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='uknown', max_length=100)),
                ('last_name', models.CharField(default='unknown', max_length=100)),
                ('rfid_tag', models.CharField(default='unknown', max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'End User',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(default='unknown', max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Shop',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PointOfSale.enduser')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PointOfSale.shop')),
            ],
            options={
                'verbose_name': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='ESP32Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('shared_secret', models.CharField(max_length=100)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PointOfSale.shop')),
            ],
            options={
                'verbose_name': 'ESP32 Controller',
            },
        ),
    ]
