# Generated by Django 4.2.1 on 2023-06-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PointOfSale', '0002_alter_esp32controller_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='first_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='rfid_tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
